#ifndef SCODES_HPP

# define SCODES_HPP

#define STATUS_CONNECTED 301
#define STATUS_DISCONNECTED 302
#define STATUS_REGISTERED 303



// RPL SECTION

#define RPL_WELCOME 101
#define RPL_YOURHOST 102
#define RPL_TOPIC 103
#define RPL_NAMREPLY 104
#define RPL_ENDOFNAMES 105
#define RPL_NAMELIST 106
#define RPL_PONG 107

// ERR SECTION

#define ERR_NOSUCHCHANNEL 201
#define ERR_NOTREGISTERED 202
#define ERR_NICKNAMEINUSE 203

// RPL_CODES

#define RPL_LOGIN_CODE "001"

#define RPL_TOPIC_CODE "332"
#define RPL_NAMELIST_CODE "353"
#define RPL_ENDOFNAMES_CODE "366"
#define ERR_NOSUCHNICK_CODE "401"
#define ERR_NOSUCHCHANNEL_CODE "403"

#endif